
path: D:\Coding & Software Development Projects\Artificial Intelligence and Machine Learning Projects\Computer Vision\yolov8_object_detection\data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes - object(s) that I am detecting
names:
  0: alpaca
